/*
 * Document Drive
 * This is a API for document viewer component
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.demo.document.documentdrive.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;

/**
 * FilesInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2020-01-09T11:02:48.153Z[GMT]")public class FilesInner   {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("type")
  private Integer type = null;

  @JsonProperty("modifiedOn")
  private Long modifiedOn = null;

  @JsonProperty("fileSize")
  private String fileSize = null;

  public FilesInner name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the file/folder
   * @return name
   **/
  @JsonProperty("name")
  @Schema(description = "Name of the file/folder")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FilesInner type(Integer type) {
    this.type = type;
    return this;
  }

  /**
   * Type of object whether file/folder
   * @return type
   **/
  @JsonProperty("type")
  @Schema(description = "Type of object whether file/folder")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public FilesInner modifiedOn(Long modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

  /**
   * Timestamp of last modified operation
   * @return modifiedOn
   **/
  @JsonProperty("modifiedOn")
  @Schema(description = "Timestamp of last modified operation")
  public Long getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(Long modifiedOn) {
    this.modifiedOn = modifiedOn;
  }

  public FilesInner fileSize(String fileSize) {
    this.fileSize = fileSize;
    return this;
  }

  /**
   * Size of the file/folder
   * @return fileSize
   **/
  @JsonProperty("fileSize")
  @Schema(description = "Size of the file/folder")
  public String getFileSize() {
    return fileSize;
  }

  public void setFileSize(String fileSize) {
    this.fileSize = fileSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilesInner filesInner = (FilesInner) o;
    return Objects.equals(this.name, filesInner.name) &&
        Objects.equals(this.type, filesInner.type) &&
        Objects.equals(this.modifiedOn, filesInner.modifiedOn) &&
        Objects.equals(this.fileSize, filesInner.fileSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, modifiedOn, fileSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilesInner {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
