spring:
  application:
    name: documentdrive
  main:
    web-application-type: none    
  security:
    oauth2:
      client:
        clientId: 727567359924-6rgerqn9n3l3llitgqjl8lsuaopv30hd.apps.googleusercontent.com
        clientSecret: BPP-uobsFHJ8pklCQO8A6ouA
      registration:
        google:
          redirect-uri: http://localhost:8080/login
      resource:
        userInfoUri: https://www.googleapis.com/userinfo/v2/me
        preferTokenInfo: false
    
server:
  port: 8080

documentdrive:
  service:
    auth:
      tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
      tokenExpirationMsec: 864000000
    oauth2:
      authorizedRedirectUris:
        - http://localhost:3000/oauth2/redirect
        - myandroidapp://oauth2/redirect
        - myiosapp://oauth2/redirect